const constants = {
  APP_OWNER: 'Myhomeetal',
  APP_NAME: 'Myhomeetal Website',
  AUTH_TOKEN: 'AUTH_TOKEN',
  USER_INFO: 'USER_INFO',
  REFRESH_TOKEN_COOKIE: 'REFRESH_TOKEN_COOKIE',
  V1_BASE_API_URL: process.env.NEXT_PUBLIC_V1_BASE_API_URL,
};

const queryKeys = {
  ALL_PRODUCTS: 'getAllProducts',
  USER: 'getUserInformation',
};

const locations = [
  { name: "Abule Egba (Agbado Ijaye Road)", fee: 500 },
  { name: "Abule Egba (Ajasa Command Rd)", fee: 510 },
  { name: "Abule Egba (Ajegunle)", fee: 520 },
  { name: "Abule Egba (Alagbado)", fee: 530 },
  { name: "Abule Egba (Alakuko)", fee: 540 },
  { name: "Abule Egba (Ekoro road)", fee: 550 },
  { name: "Abule Egba (Meiran Road)", fee: 560 },
  { name: "Abule Egba (New Oko Oba)", fee: 570 },
  { name: "Abule Egba (Old Otta Road)", fee: 580 },
  { name: "Agbara", fee: 590 },
  { name: "Agege (Ajuwon Akute Road)", fee: 600 },
  { name: "Agege (Dopemu)", fee: 610 },
  { name: "Agege (Iju Road)", fee: 620 },
  { name: "Agege (Old Abeokuta Road)", fee: 630 },
  { name: "Agege (Orile Agege)", fee: 640 },
  { name: "AGUNGI (LEKKI)", fee: 650 },
  { name: "AJAO ESTATE", fee: 660 },
  { name: "AMUWO", fee: 670 },
  { name: "ANTHONY VILLAGE", fee: 680 },
  { name: "Apapa (Ajegunle)", fee: 690 },
  { name: "Ayobo (Ipaja)", fee: 700 },
  { name: "Badagry (Ibereko)", fee: 710 },
  { name: "Bariga (Shomolu)", fee: 720 },
  { name: "Egbeda (Alimosho)", fee: 730 },
  { name: "Epe (Ijebu Oloja)", fee: 740 },
  { name: "Festac Town (Amuwo Odofin)", fee: 750 },
  { name: "Gbagada (Kosofe)", fee: 760 },
  { name: "Ibeju-Lekki (Awoyaya)", fee: 770 },
  { name: "Idimu (Alimosho)", fee: 780 },
  { name: "Ifako-Ijaiye (Ogba)", fee: 790 },
  { name: "Ijede (Ikorodu)", fee: 800 },
  { name: "Ikeja (GRA)", fee: 810 },
  { name: "Ikorodu (Imota)", fee: 820 },
  { name: "Ikotun (Alimosho)", fee: 830 },
  { name: "Ilasamaja (Mushin)", fee: 840 },
  { name: "Ilupeju (Mushin)", fee: 850 },
  { name: "Ipaja (Ayobo)", fee: 860 },
  { name: "Isolo (Okota)", fee: 870 },
  { name: "Itire (Surulere)", fee: 880 },
  { name: "Iyana Ipaja (Alimosho)", fee: 890 },
  { name: "Ketu (Kosofe)", fee: 900 },
  { name: "Kosofe (Mile 12)", fee: 910 },
  { name: "Lagos Island (Obalende)", fee: 920 },
  { name: "Lagos Mainland (Ebute Metta)", fee: 930 },
  { name: "Lekki (Phase 1)", fee: 940 },
  { name: "Magodo (Shangisha)", fee: 950 },
  { name: "Maryland (Ikeja)", fee: 960 },
  { name: "Mushin (Idi-Oro)", fee: 970 },
  { name: "Ogba (Ifako-Ijaiye)", fee: 980 },
  { name: "Ogudu (Kosofe)", fee: 990 },
  { name: "Ojo (Alaba)", fee: 1000 },
  { name: "Ojodu (Berger)", fee: 1010 },
  { name: "Ojota (Kosofe)", fee: 1020 },
  { name: "Oke-Odo (Abule Egba)", fee: 1030 },
  { name: "Okokomaiko (Ojo)", fee: 1040 },
  { name: "Onigbongbo (Maryland)", fee: 1050 },
  { name: "Orile (Iganmu)", fee: 1060 },
  { name: "Oshodi (Isolo)", fee: 1070 },
  { name: "Shomolu (Bariga)", fee: 1080 },
  { name: "Surulere (Ojuelegba)", fee: 1090 },
  { name: "Victoria Island (VI)", fee: 1100 },
  { name: "Yaba (Sabo)", fee: 1110 }
];

export { constants, queryKeys, locations };
